### ISSUE TITLE
Error while install library due pip on macOS

### ISSUE THREAD

**Issue by hamsternik** [FabriceSalvaire/PyOpenGLng#21]
Hi, folks!

Today I faced with a problem to install PyOpenGLng on my macOS system. OS X version is 10.12.

As wrote into readme, I just typed `pip install PyOpenGLng` and get next error (screen attached).

<img width="1046" alt="screenshot 2017-09-26 23 36 41" src="https://user-images.githubusercontent.com/4441804/30883037-a2210a6a-a313-11e7-9273-a849103820f4.png">

So, how knows how to fix this, please, get the answer or go into this issue to discuss that trouble.

**Comment by FabriceSalvaire** [comment]
You must use Python 3

**Comment by hamsternik** [comment]
That's it! Thanks for your quick help. 

I guess, you can add a small note into README about the concrete `pip` version.
